# Generated by Django 5.2.4 on 2025-08-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(blank=True, verbose_name='Left/Intro Text')),
                ('newsletter_text', models.CharField(blank=True, max_length=255, verbose_name='Newsletter Text')),
                ('contact_address', models.CharField(max_length=255, verbose_name='Contact Address')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_website', models.URLField(blank=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
