# Generated by Django 5.2.4 on 2025-08-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footer_model_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
    ]
