# Generated by Django 5.2.4 on 2025-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_social_media_fields_added_to_footer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MostTrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='URL to the trending post/video/article')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='most_trending/')),
                ('expiry_date', models.DateField(blank=True, help_text='Date after which event is archived and hidden from display', null=True, verbose_name='Expiry Date')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='events/')),
                ('event_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Date after which event is archived and hidden from display', null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='events', to='core.category')),
            ],
        ),
    ]
