# Generated by Django 5.2.4 on 2025-08-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_models_for_event_and_trending_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='mosttrending',
            options={'ordering': ['-created_at'], 'verbose_name': 'Most Trending', 'verbose_name_plural': 'Most Trending'},
        ),
    ]
