# Generated by Django 5.2.4 on 2025-08-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_options_alter_mosttrending_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
