# Generated by Django 5.2.4 on 2025-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(choices=[('address', 'Address'), ('phone', 'Phone'), ('email', 'Email')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('extra_info', models.CharField(blank=True, max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class like ti-home, ti-tablet, ti-email', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'ordering': ['info_type'],
            },
        ),
    ]
