# Generated by Django 5.2.4 on 2025-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
