# Generated by Django 5.2.4 on 2025-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_introduction_model_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Introdution',
            new_name='Introduction',
        ),
    ]
