# Generated by Django 5.2.4 on 2025-08-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_introdution_renamed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['created_at'], 'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
    ]
