# Generated by Django 5.2.4 on 2025-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='director',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='director',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='director',
            name='skype_url',
            field=models.URLField(blank=True, verbose_name='Skype URL'),
        ),
        migrations.AddField(
            model_name='director',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='director',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
    ]
