# Generated by Django 5.2.4 on 2025-08-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_social_media_fields_added_to_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
