# Generated by Django 5.2.4 on 2025-08-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_gender_field_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['created_at'], 'verbose_name': 'Director', 'verbose_name_plural': 'Board of Directors'},
        ),
    ]
