# Generated by Django 5.2.4 on 2025-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_director_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='team_type',
            field=models.CharField(choices=[('management', 'Management'), ('technical', 'Technical')], default='management', max_length=20),
        ),
    ]
