# Generated by Django 5.2.4 on 2025-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_team_type_field_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='director',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first'),
        ),
        migrations.AlterField(
            model_name='director',
            name='team_type',
            field=models.CharField(choices=[('trustee', 'Trustee'), ('management', 'Management')], default='trustee', max_length=20),
        ),
    ]
